[package]
name = "phoenix-tls"
version = "0.1.0"
authors = ["tyler <tyler@brainiumstudios.com>"]
edition = "2018"

[features]
default = ["std"]
nightly = ["nudge/nightly"]
std = ["nudge/std"]

[dependencies]
cfg-if = "0.1.9"
nudge = "0.1.0"

[dev-dependencies]
lazy_static = "1.3.0"
